<a href="https://colab.research.google.com/github/kushalmiglani01/ML/blob/master/Apartment_Listing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
def _load_listings_data():
    """
    Returns the Airbnb listings dataset as a pd.DataFrame.
    """
    return pd.read_csv("https://storage.googleapis.com/public-data-337819/listings%202%20reduced.csv", low_memory=False)

def _load_reviews_data():
    """
    Returns the Airbnb reviews dataset as a pd.DataFrame.
    """
    return pd.read_csv("https://storage.googleapis.com/public-data-337819/reviews%202%20reduced.csv", low_memory=False)

def load_data():
    """
    Returns the Airbnb listings and reviews datasets as a tuple of pd.DataFrame.
    """
    return _load_listings_data(), _load_reviews_data()

In [ ]:
df_listings, df_reviews = load_data()

### TASK 1

In [ ]:
# Task 1
df_listings["price"] = df_listings["price"].str.replace("[$,]", "", regex=True).astype(float)

In [ ]:
grouped = (df_listings
           .groupby(
                ['neighbourhood_cleansed', 'host_is_superhost']
              )['price']
           .median()
           .unstack()
          )

grouped['median_price_dff'] = abs(grouped['f'] - grouped['t'])
grouped.median_price_dff.idxmax()

'Westminster'

### TASK 2

In [ ]:
# Task 2

rel_columns = [
    'review_scores_rating',
    'review_scores_accuracy',
    'review_scores_cleanliness',
    'review_scores_checkin',
    'review_scores_communication',
    'review_scores_location',
    'review_scores_value',
    'price'
]

df_rel_t2 = df_listings[rel_columns]

In [ ]:
corr = df_rel_t2.corr()

In [ ]:
corr_price = corr['price']

In [ ]:
corr_price.drop('price', inplace=True)

In [ ]:
corr_price

review_scores_rating          -0.001427
review_scores_accuracy        -0.018796
review_scores_cleanliness      0.000411
review_scores_checkin         -0.026650
review_scores_communication   -0.030010
review_scores_location         0.025984
review_scores_value           -0.031564
Name: price, dtype: float64

In [ ]:
abs(corr_price).idxmax()

'review_scores_value'

### TASK 3

In [ ]:
df_listings.head(2)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,92644,https://www.airbnb.com/rooms/92644,20230906022807,2023-09-06,city scrape,Rental unit in Earlsfield · ★4.57 · 1 bedroom ...,<b>The space</b><br />Hi everyone! I have 2 ro...,NaN,https://a0.muscache.com/pictures/715127/85bdb4...,498201,https://www.airbnb.com/users/show/498201,Dee Dee,2011-04-10,"London, United Kingdom",I am employed at St Georges hospital in tootin...,NaN,NaN,100%,f,https://a0.muscache.com/im/pictures/user/0edcb...,https://a0.muscache.com/im/pictures/user/0edcb...,Earlsfield,1.0,1.0,"['email', 'phone']",t,t,NaN,Wandsworth,NaN,51.44201,-0.18739,Private room in rental unit,Private room,2,NaN,1.5 shared baths,NaN,2.0,"[""Heating"", ""TV with standard cable"", ""Wifi"", ...",42.0,2,730,2.0,2.0,1125.0,1125.0,2.0,1125.0,NaN,t,0,0,0,217,2023-09-06,216,9,0,2011-06-21,2022-10-29,4.57,4.74,4.86,4.71,4.67,4.53,4.68,NaN,t,1,0,1,0,1.45
1,93015,https://www.airbnb.com/rooms/93015,20230906022807,2023-09-06,city scrape,Rental unit in Hammersmith · ★4.82 · 2 bedroom...,Gorgeous 2 bed ground floor apartment with per...,A bit of history about the W14 area: <br />Com...,https://a0.muscache.com/pictures/865937ec-ee56...,499704,https://www.airbnb.com/users/show/499704,Sarah,2011-04-11,"London, United Kingdom",Been living in London for over 20 years and I ...,within a few hours,100%,25%,f,https://a0.muscache.com/im/pictures/user/452ff...,https://a0.muscache.com/im/pictures/user/452ff...,Hammersmith,1.0,2.0,"['email', 'phone']",t,t,"Hammersmith, England, United Kingdom",Hammersmith and Fulham,NaN,51.49993,-0.21707,Entire rental unit,Entire home/apt,5,NaN,1 bath,2.0,3.0,"[""Window guards"", ""Bathtub"", ""Hot water kettle...",175.0,5,240,5.0,5.0,240.0,240.0,5.0,240.0,NaN,t,13,18,38,40,2023-09-06,38,2,0,2012-02-01,2022-09-30,4.82,4.76,4.62,4.85,4.88,4.85,4.74,NaN,f,1,1,0,0,0.27

In [ ]:
host_w_loc_cnt = df_listings.groupby('host_id')['neighbourhood_cleansed'].nunique()

In [ ]:
profesionnal_hosts = host_w_loc_cnt[host_w_loc_cnt > 5].index

In [ ]:
len(profesionnal_hosts)

145

In [ ]:
df_listings['host_is_pro'] = df_listings['host_id'].isin(profesionnal_hosts)

In [ ]:
df_listings.host_is_pro.value_counts()

host_is_pro
False    80826
True      7120
Name: count, dtype: int64

In [ ]:
avg_price_pro_host = df_listings.groupby('host_is_pro')['price'].mean().to_frame().transpose()

In [ ]:
avg_price_pro_host.columns

Index([False, True], dtype='bool', name='host_is_pro')

In [ ]:
abs(avg_price_pro_host[True] - avg_price_pro_host[False]).values

array([285.70509482])

### TASK 4

In [ ]:
df_listings.room_type.value_counts()

room_type
Entire home/apt    54575
Private room       32711
Shared room          441
Hotel room           219
Name: count, dtype: int64

In [ ]:
entire_homes = df_listings[df_listings['room_type'].isin(['Entire home/apt'])]
other_listings = df_listings[~df_listings['room_type'].isin(['Entire home/apt'])]

median_prices = df_listings.groupby(['neighbourhood_cleansed', 'room_type'])['price'].median().unstack()

In [ ]:
entire_homes.head(2)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_is_pro
1,93015,https://www.airbnb.com/rooms/93015,20230906022807,2023-09-06,city scrape,Rental unit in Hammersmith · ★4.82 · 2 bedroom...,Gorgeous 2 bed ground floor apartment with per...,A bit of history about the W14 area: <br />Com...,https://a0.muscache.com/pictures/865937ec-ee56...,499704,https://www.airbnb.com/users/show/499704,Sarah,2011-04-11,"London, United Kingdom",Been living in London for over 20 years and I ...,within a few hours,100%,25%,f,https://a0.muscache.com/im/pictures/user/452ff...,https://a0.muscache.com/im/pictures/user/452ff...,Hammersmith,1.0,2.0,"['email', 'phone']",t,t,"Hammersmith, England, United Kingdom",Hammersmith and Fulham,NaN,51.49993,-0.21707,Entire rental unit,Entire home/apt,5,NaN,1 bath,2.0,3.0,"[""Window guards"", ""Bathtub"", ""Hot water kettle...",175.0,5,240,5.0,5.0,240.0,240.0,5.0,240.0,NaN,t,13,18,38,40,2023-09-06,38,2,0,2012-02-01,2022-09-30,4.82,4.76,4.62,4.85,4.88,4.85,4.74,NaN,f,1,1,0,0,0.27,False
3,15400,https://www.airbnb.com/rooms/15400,20230906022807,2023-09-06,city scrape,Rental unit in London · ★4.80 · 1 bedroom · 1 ...,Lots of windows and light. St Luke's Gardens ...,It is Chelsea.,https://a0.muscache.com/pictures/428392/462d26...,60302,https://www.airbnb.com/users/show/60302,Philippa,2009-12-05,"Royal Borough of Kensington and Chelsea, Unite...","English, grandmother, I have travelled quite ...",within a day,100%,41%,f,https://a0.muscache.com/im/users/60302/profile...,https://a0.muscache.com/im/users/60302/profile...,Chelsea,1.0,12.0,"['email', 'phone']",t,t,"London, United Kingdom",Kensington and Chelsea,NaN,51.48780,-0.16813,Entire rental unit,Entire home/apt,2,NaN,1 bath,1.0,1.0,"[""Shampoo"", ""Luggage dropoff allowed"", ""Dryer""...",150.0,7,30,7.0,7.0,30.0,30.0,7.0,30.0,NaN,t,7,7,7,73,2023-09-06,94,5,0,2009-12-21,2023-05-01,4.80,4.85,4.88,4.88,4.83,4.93,4.74,NaN,f,1,1,0,0,0.56,False

In [ ]:
median_prices

room_type               Entire home/apt  Hotel room  Private room  Shared room
neighbourhood_cleansed
Barking and Dagenham              140.0         NaN          45.0         70.0
Barnet                            134.0       103.0          54.0         25.5
Bexley                            123.0         NaN          45.0         65.5
Brent                             133.0         NaN          59.0         48.5
Bromley                           110.0         NaN          50.0         85.5
Camden                            177.0       135.5          70.0         50.0
City of London                    176.0         NaN         100.0        103.5
Croydon                           100.0       111.0          44.5         25.0
Ealing                            134.0         NaN          50.0         50.0
Enfield                           130.0        89.0          50.0         48.5
Greenwich                         142.5       170.0          50.0         47.5
Hackney                           134.0       152.0          50.0         49.0
Hammersmith and Fulham            160.0       146.5          63.0         43.0
Haringey                          120.0        95.0          47.0         30.0
Harrow                            127.0         NaN          45.0         55.0
Havering                          143.0         NaN          47.0         50.0
Hillingdon                        133.0         NaN          55.0         55.0
Hounslow                          145.0       220.0          50.0        100.0
Islington                         143.0       180.0          60.0         30.0
Kensington and Chelsea            209.0       275.0          88.0         44.0
Kingston upon Thames              135.0         NaN          50.0          NaN
Lambeth                           140.0        35.0          55.0         45.5
Lewisham                          113.0         NaN          45.0         30.0
Merton                            156.0         NaN          54.0         35.0
Newham                            151.0       209.5          50.0         45.0
Redbridge                         128.5         NaN          48.0         60.0
Richmond upon Thames              160.0       336.0          64.0         85.0
Southwark                         150.0       100.5          59.5         56.0
Sutton                            115.0         NaN          45.0         48.0
Tower Hamlets                     148.0       160.0          54.0         34.0
Waltham Forest                    117.0         NaN          48.0         32.5
Wandsworth                        155.0       217.0          59.0         49.5
Westminster                       230.0       363.5          90.0         47.5

In [ ]:
median_prices['premium'] = (median_prices['Entire home/apt'] - median_prices.drop(columns=['Entire home/apt']).median(axis=1)) / median_prices.drop(columns=['Entire home/apt']).median(axis=1)

In [ ]:
median_prices

room_type,Entire home/apt,Hotel room,Private room,Shared room,premium
neighbourhood_cleansed,,,,,
Barking and Dagenham,140.0,NaN,45.0,70.0,1.434783
Barnet,134.0,103.0,54.0,25.5,1.481481
Bexley,123.0,NaN,45.0,65.5,1.226244
Brent,133.0,NaN,59.0,48.5,1.474419
Bromley,110.0,NaN,50.0,85.5,0.623616
Camden,177.0,135.5,70.0,50.0,1.528571
City of London,176.0,NaN,100.0,103.5,0.729730
Croydon,100.0,111.0,44.5,25.0,1.247191
Ealing,134.0,NaN,50.0,50.0,1.680000
Enfield,130.0,89.0,50.0,48.5,1.600000
Greenwich,142.5,170.0,50.0,47.5,1.850000
Hackney,134.0,152.0,50.0,49.0,1.680000
Hammersmith and Fulham,160.0,146.5,63.0,43.0,1.539683
Haringey,120.0,95.0,47.0,30.0,1.553191
Harrow,127.0,NaN,45.0,55.0,1.540000
Havering,143.0,NaN,47.0,50.0,1.948454
Hillingdon,133.0,NaN,55.0,55.0,1.418182
Hounslow,145.0,220.0,50.0,100.0,0.450000
Islington,143.0,180.0,60.0,30.0,1.383333
Kensington and Chelsea,209.0,275.0,88.0,44.0,1.375000
Kingston upon Thames,135.0,NaN,50.0,NaN,1.700000
Lambeth,140.0,35.0,55.0,45.5,2.076923
Lewisham,113.0,NaN,45.0,30.0,2.013333
Merton,156.0,NaN,54.0,35.0,2.505618
Newham,151.0,209.5,50.0,45.0,2.020000
Redbridge,128.5,NaN,48.0,60.0,1.379630
Richmond upon Thames,160.0,336.0,64.0,85.0,0.882353
Southwark,150.0,100.5,59.5,56.0,1.521008
Sutton,115.0,NaN,45.0,48.0,1.473118
Tower Hamlets,148.0,160.0,54.0,34.0,1.740741
Waltham Forest,117.0,NaN,48.0,32.5,1.906832
Wandsworth,155.0,217.0,59.0,49.5,1.627119
Westminster,230.0,363.5,90.0,47.5,1.555556

In [ ]:
avg_premium = median_prices['premium'].mean()
print(f"Average Price Premium for Entire Homes/Apartments: {avg_premium:.2f}")

Average Price Premium for Entire Homes/Apartments: 1.52

### TASK 5

In [ ]:
filtered_listings = df_listings[df_listings['minimum_nights'] <= 7]

# Get reviews from the last 12 months
df_reviews['date'] = pd.to_datetime(df_reviews['date'])
recent_reviews = df_reviews[df_reviews['date'] >= pd.Timestamp.now() - pd.DateOffset(months=24)]

# Calculate occupancy based on reviews
occupancy = recent_reviews.groupby('listing_id')['id'].count().reset_index()
occupancy['estimated_bookings'] = (occupancy['id'] / 0.6).astype(int)
occupancy.rename(columns={'id': 'review_count'}, inplace=True)

In [ ]:
occupancy.head()

   listing_id  review_count  estimated_bookings
0       15400             2                   3
1       31036             2                   3
2       36299             7                  11
3       36660            40                  66
4       38610             2                   3

In [ ]:
# Merge occupancy with filtered listings
filtered_listings = pd.merge(filtered_listings,
                             occupancy, left_on='id',
                             right_on = 'listing_id', how='left')

In [ ]:
filtered_listings.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_is_pro,host_since_days,host_is_superhost_cleaned,listing_id,review_count,estimated_bookings
0,92644,https://www.airbnb.com/rooms/92644,20230906022807,2023-09-06,city scrape,Rental unit in Earlsfield · ★4.57 · 1 bedroom ...,<b>The space</b><br />Hi everyone! I have 2 ro...,NaN,https://a0.muscache.com/pictures/715127/85bdb4...,498201,https://www.airbnb.com/users/show/498201,Dee Dee,2011-04-10,"London, United Kingdom",I am employed at St Georges hospital in tootin...,NaN,NaN,100%,f,https://a0.muscache.com/im/pictures/user/0edcb...,https://a0.muscache.com/im/pictures/user/0edcb...,Earlsfield,1.0,1.0,"['email', 'phone']",t,t,NaN,Wandsworth,NaN,51.44201,-0.18739,Private room in rental unit,Private room,2,NaN,1.5 shared baths,NaN,2.0,"[""Heating"", ""TV with standard cable"", ""Wifi"", ...",42.0,2,730,2.0,2.0,1125.0,1125.0,2.0,1125.0,NaN,t,0,0,0,217,2023-09-06,216,9,0,2011-06-21,2022-10-29,4.57,4.74,4.86,4.71,4.67,4.53,4.68,NaN,t,1,0,1,0,1.45,False,464.0,0.0,NaN,NaN,NaN
1,93015,https://www.airbnb.com/rooms/93015,20230906022807,2023-09-06,city scrape,Rental unit in Hammersmith · ★4.82 · 2 bedroom...,Gorgeous 2 bed ground floor apartment with per...,A bit of history about the W14 area: <br />Com...,https://a0.muscache.com/pictures/865937ec-ee56...,499704,https://www.airbnb.com/users/show/499704,Sarah,2011-04-11,"London, United Kingdom",Been living in London for over 20 years and I ...,within a few hours,100%,25%,f,https://a0.muscache.com/im/pictures/user/452ff...,https://a0.muscache.com/im/pictures/user/452ff...,Hammersmith,1.0,2.0,"['email', 'phone']",t,t,"Hammersmith, England, United Kingdom",Hammersmith and Fulham,NaN,51.49993,-0.21707,Entire rental unit,Entire home/apt,5,NaN,1 bath,2.0,3.0,"[""Window guards"", ""Bathtub"", ""Hot water kettle...",175.0,5,240,5.0,5.0,240.0,240.0,5.0,240.0,NaN,t,13,18,38,40,2023-09-06,38,2,0,2012-02-01,2022-09-30,4.82,4.76,4.62,4.85,4.88,4.85,4.74,NaN,f,1,1,0,0,0.27,False,465.0,0.0,NaN,NaN,NaN
2,13913,https://www.airbnb.com/rooms/13913,20230906022807,2023-09-06,city scrape,Rental unit in Islington · ★4.80 · 1 bedroom ·...,My bright double bedroom with a large window h...,Finsbury Park is a friendly melting pot commun...,https://a0.muscache.com/pictures/miso/Hosting-...,54730,https://www.airbnb.com/users/show/54730,Alina,2009-11-16,"London, United Kingdom",I am a Multi-Media Visual Artist and Creative ...,within a few hours,100%,88%,f,https://a0.muscache.com/im/users/54730/profile...,https://a0.muscache.com/im/users/54730/profile...,LB of Islington,3.0,4.0,"['email', 'phone']",t,t,"Islington, Greater London, United Kingdom",Islington,NaN,51.56861,-0.11270,Private room in rental unit,Private room,1,NaN,1 shared bath,NaN,1.0,"[""Bathtub"", ""Hot water kettle"", ""Laundromat ne...",79.0,1,29,1.0,1.0,29.0,29.0,1.0,29.0,NaN,t,25,55,85,360,2023-09-06,41,11,0,2010-08-18,2022-12-11,4.80,4.72,4.72,4.74,4.82,4.69,4.69,NaN,f,2,1,1,0,0.26,False,-46.0,0.0,NaN,NaN,NaN
3,15400,https://www.airbnb.com/rooms/15400,20230906022807,2023-09-06,city scrape,Rental unit in London · ★4.80 · 1 bedroom · 1 ...,Lots of windows and light. St Luke's Gardens ...,It is Chelsea.,https://a0.muscache.com/pictures/428392/462d26...,60302,https://www.airbnb.com/users/show/60302,Philippa,2009-12-05,"Royal Borough of Kensington and Chelsea, Unite...","English, grandmother, I have travelled quite ...",within a day,100%,41%,f,https://a0.muscache.com/im/users/60302/profile...,https://a0.muscache.com/im/users/60302/profile...,Chelsea,1.0,12.0,"['email', 'phone']",t,t,"London, United Kingdom",Kensington and Chelsea,NaN,51.48780,-0.16813,Entire rental unit,Entire home/apt,2,NaN,1 bath,1.0,1.0,"[""Shampoo"", ""Luggage dropoff allowed"", ""Dryer""...",150.0,7,30,7.0,7.0,30.0,30.0,7.0,30.0,NaN,t,7,7,7,73,2023-09-06,94,5,0,2009-12-21,2023-05-01,4.80,4.85,4.88,4.88,4.83,4.93,4.74,NaN,f,1,1,0,0,0.56,False,-27.0,0.0,15400.0,2.0,3.0
4,93734,https://www.airbnb.com/rooms/93734,20230906022807,2023-09-07,city scrape,Condo in London · ★4.62 · 1 bedroom · 1 bed · ...,<b>During your stay</b><br />I’m a professiona...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,497514,https://www.airbnb.com/users/show/497514,William,2011-04-10,"London, United Kingdom",I’m a maverick by nature. Restless and curious...,within a few hours,90%,75%,t,https://a0.muscache.com/im/users/497514/profil...,https://a0.muscache.com/im/users/497514/profil...,Greenwich,1.0,1.0,"['email', 'phone']",t,t,NaN,Greenwich,NaN,51.47618,0.01442,Private room in condo,Private room,2,NaN,1 shared bath,NaN,1.0,"[""Window guards"", ""Bathtub"", ""Hot water kettle...",46.0,4,365,2.0,4.0,365.0,365.0,4.0,365.0,NaN,t,5,5,5,196,2023-09-07,180,25,3,2011-06-30,2023-09-02,4.62,4.70,4.59,4.63,4.81,4.64,4.67,NaN,f,1,0,1,0,1.21,False,464.0,1.0,93734.0,12.0,20.0

In [ ]:

filtered_listings['estimated_bookings'].fillna(0, inplace=True)

# Calculate expected revenue
filtered_listings['expected_revenue'] = filtered_listings['estimated_bookings'] * filtered_listings['price'] * filtered_listings['minimum_nights']

# Find the listing with the best expected revenue
best_listing = filtered_listings.loc[filtered_listings['expected_revenue'].idxmax()]

# Display the listing ID
print(f"Listing ID with the best expected revenue: {best_listing['id']}")

Listing ID with the best expected revenue: 6611450

<ipython-input-60-1249865ee1a0>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  filtered_listings['estimated_bookings'].fillna(0, inplace=True)

In [ ]:
best_listing

id                                                                                        6611450
listing_url                                                  https://www.airbnb.com/rooms/6611450
scrape_id                                                                          20230906022807
last_scraped                                                                           2023-09-06
source                                                                                city scrape
name                                            Condo in Greater London · ★4.36 · 1 bedroom · ...
description                                     My neighborhood Crouch End was chosen by The S...
neighborhood_overview                           Crouch End has a village feel, and not having ...
picture_url                                     https://a0.muscache.com/pictures/miso/Hosting-...
host_id                                                                                  11842647
host_url                                               https://www.airbnb.com/users/show/11842647
host_name                                                                                  Daniel
host_since                                                                             2014-02-01
host_location                                                              London, United Kingdom
host_about                                      I'm a single dad with two kids who's also a br...
host_response_time                                                                 within an hour
host_response_rate                                                                           100%
host_acceptance_rate                                                                          85%
host_is_superhost                                                                               f
host_thumbnail_url                              https://a0.muscache.com/im/pictures/user/29e3e...
host_picture_url                                https://a0.muscache.com/im/pictures/user/29e3e...
host_neighbourhood                                                                            NaN
host_listings_count                                                                           1.0
host_total_listings_count                                                                     3.0
host_verifications                                                             ['email', 'phone']
host_has_profile_pic                                                                            t
host_identity_verified                                                                          t
neighbourhood                                             Greater London, England, United Kingdom
neighbourhood_cleansed                                                                   Haringey
neighbourhood_group_cleansed                                                                  NaN
latitude                                                                                51.580395
longitude                                                                                -0.11124
property_type                                                               Private room in condo
room_type                                                                            Private room
accommodates                                                                                    3
bathrooms                                                                                     NaN
bathrooms_text                                                                   1.5 shared baths
bedrooms                                                                                      NaN
beds                                                                                          2.0
amenities                                       ["Bathtub", "Hot water kettle", "Laundromat ne...
price                                                                                      6000.0
minimum_nights                                                                                  3
maximum_nights                                                                                 12
minimum_minimum_nights                                                                        3.0
maximum_minimum_nights                                                                        3.0
minimum_maximum_nights                                                                       12.0
maximum_maximum_nights                                                                       12.0
minimum_nights_avg_ntm                                                                        3.0
maximum_nights_avg_ntm                                                                       12.0
calendar_updated                                                                              NaN
has_availability                                                                                t
availability_30                                                                                12
availability_60                                                                                42
availability_90                                                                                72
availability_365                                                                               72
calendar_last_scraped                                                                  2023-09-06
number_of_reviews                                                                              28
number_of_reviews_ltm                                                                          28
number_of_reviews_l30d                                                                          0
first_review                                                                           2022-09-11
last_review                                                                            2023-07-23
review_scores_rating                                                                         4.36
review_scores_accuracy                                                                        4.5
review_scores_cleanliness                                                                     4.0
review_scores_checkin                                                                        4.82
review_scores_communication                                                                  4.79
review_scores_location                                                                        4.5
review_scores_value                                                                          4.46
license                                                                                       NaN
instant_bookable                                                                                f
calculated_host_listings_count                                                                  1
calculated_host_listings_count_entire_homes                                                     0
calculated_host_listings_count_private_rooms                                                    1
calculated_host_listings_count_shared_rooms                                                     0
reviews_per_month                                                                            2.33
host_is_pro                                                                                 False
host_since_days                                                                            1492.0
host_is_superhost_cleaned                                                                     0.0
listing_id                                                                              6611450.0
review_count                                                                                 17.0
estimated_bookings                                                                           28.0
expected_revenue                                                                         504000.0
Name: 4448, dtype: object

### TASK 6

In [ ]:
avg_review_dff_super_host = df_listings.groupby('host_is_superhost')['review_scores_rating'].mean().to_frame().transpose()

In [ ]:
avg_review_dff_super_host

host_is_superhost            f         t
review_scores_rating  4.534971  4.858306

In [ ]:
abs(avg_review_dff_super_host['t'] - avg_review_dff_super_host['f']).values

array([0.32333493])

### TASK 7

In [ ]:
df_listings.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month',
       'host_is_pro'],
      dtype='object')

In [ ]:
host_attributes = ['host_since', 'host_listings_count', 'host_identity_verified', 'calculated_host_listings_count', 'host_is_superhost']
target_variable = 'number_of_reviews'
df_subset = df_listings[[target_variable] + host_attributes]
df_subset.loc[:,'host_since'] = pd.to_datetime(df_subset['host_since']).sub(pd.Timestamp('2010-01-01')).dt.days
df_subset.loc[:,'host_is_superhost'] = df_subset['host_is_superhost'].map({'t': 1, 'f': 0})
df_subset.loc[:,'host_identity_verified'] = df_subset['host_identity_verified'].map({'t': 1, 'f': 0})

In [ ]:
df_subset.head(2)

,number_of_reviews,host_since,host_listings_count,host_identity_verified,calculated_host_listings_count,host_is_superhost
0,216,464.0,1.0,1.0,1,0.0
1,38,465.0,1.0,1.0,1,0.0

In [ ]:
correlations = df_subset.corr()[target_variable].drop(target_variable)

In [ ]:
second_strongest_attribute = correlations.abs().sort_values(ascending=False).index[1]
print(f"The host attribute with the second-strongest correlation with the number of reviews is: {second_strongest_attribute}")

The host attribute with the second-strongest correlation with the number of reviews is: host_since